name: PassportFlix
options:
  bundleIdPrefix: nl.tijdvoorandersom
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

packages:
  AMSMB2:
    url: https://github.com/amosavian/AMSMB2
    from: 3.0.0

targets:
  PassportFlix:
    type: application
    platform: iOS
    sources:
      - Sources
    dependencies:
      - package: AMSMB2
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: nl.tijdvoorandersom.passportflix
        INFOPLIST_FILE: Sources/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        SUPPORTS_MACCATALYST: NO
